# Generated by Django 4.2 on 2023-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='photos')),
                ('caption', models.CharField(max_length=255)),
                ('caption_vector', models.JSONField(blank=True, null=True)),
                ('names', models.CharField(max_length=255)),
                ('name_vector', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
