# Generated by Django 4.2 on 2023-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBIR_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
