# Generated by Django 4.2 on 2023-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBIR_app', '0002_remove_photo_image_path_photo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='geo_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='geolocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
